cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key:
      secret-key:
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/264271930585/ni-queue
server:
  port: 9192

logging:
  level:
    org:
      springframework:
        cloud:
          aws: DEBUG